name: Delivery API Pipeline - Paulo Carlos

on:
  push: 
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  sast:
    name: 0. SAST (Segurança)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Executar Análise SAST (njsscan)
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

  lint-and-quality:
    name: 1. Lint & Quality
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          
      - run: npm install
      
      - name: Executar Linter (ESLint)
        run: npm run lint

  test:
    name: 2. Test
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          
      - run: npm install
      - name: Executar Testes Unitários
        run: npm test